version: '3.7'
services:
  kb-container:
    container_name: kb-container
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-1:9200
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION:-latest}
    networks:
      - ${GLOBAL_NETWORK:-elastic}

  elastic-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-latest}
    hostname: elastic-1
    environment:
      - node.name=elastic-1
      - cluster.name=es-twitter-cluster
      - discovery.seed_hosts=elastic-2,elastic-3
      - cluster.initial_master_nodes=elastic-1,elastic-2,elastic-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - test-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}
  elastic-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - node.name=elastic-2
      - cluster.name=es-twitter-cluster
      - discovery.seed_hosts=elastic-1,elastic-3
      - cluster.initial_master_nodes=elastic-1,elastic-2,elastic-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - test-data02:/usr/share/elasticsearch/data
    networks:
      - ${GLOBAL_NETWORK:-elastic}
  elastic-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - node.name=elastic-3
      - cluster.name=es-twitter-cluster
      - discovery.seed_hosts=elastic-1,elastic-2
      - cluster.initial_master_nodes=elastic-1,elastic-2,elastic-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - test-data03:/usr/share/elasticsearch/data
    networks:
      - ${GLOBAL_NETWORK:-elastic}

volumes:
  test-data01:
    driver: local
  test-data02:
    driver: local
  test-data03:
    driver: local