PUT http://localhost:9200/post-index
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "id": {
        "type": "keyword"
      },
      "owner": {
        "type": "keyword"
      },
      "content": {
        "type": "text",
        "analyzer": "english"
      },
      "topic": {
        "type": "text",
        "analyzer": "english",
        "copy_to": ["topic_fuzzy"]
      },
      "topic_fuzzy": {
        "type": "text",
        "analyzer": "english"
      },
      "createdAt": {
        "type": "date",
        "format": "YYYY-MM-DD'T'HH:mm:ssZ"
      },
      "replies": {
        "type": "nested",
        "properties": {
          "id": {
            "type": "keyword"
          },
          "content": {
            "type": "text",
            "analyzer": "english"
          },
          "owner": {
            "type": "text",
            "analyzer": "english"
          },
          "createdAt": {
            "type": "date",
            "format": "YYYY-MM-DD'T'HH:mm:ssZ"
          }
        }
      }
    }
  }
}