elastic-config:
  index-name: post-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

logging:
  level:
    org:
      elasticsearch: TRACE



server:
  port: 8081
