package com.rolandsall.elastic.search.spring.template.runner;

import com.rolandsall.elastic.search.spring.template.core.application.post.command.IPostCreator;
import com.rolandsall.elastic.search.spring.template.core.domain.Comment;
import com.rolandsall.elastic.search.spring.template.core.domain.Owner;
import com.rolandsall.elastic.search.spring.template.core.domain.Post;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Service;

import java.time.ZonedDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
public class SeedData implements CommandLineRunner {

    private final IPostCreator postCreator;

    @Override
    public void run(String... args) throws Exception {
        postCreator.addPost(Post.builder()
                        .content("This is generated by the command liner runner")
                        .createdAt(ZonedDateTime.now())
                        .owner(Owner.builder()
                                .id("00000-0000-00000-00000")
                                .email("therunner@outlook.com")
                                .name("Command Line")
                                .build())
                        .replies(List.of(
                                Comment.builder()
                                        .content("You behaved well")
                                        .owner(Owner.builder()
                                                .id("22222-2222-22222-22222")
                                                .name("Martin Fowler")
                                                .email("martinFowler@outlook.com")
                                                .build())
                                        .build()

                        ))

                .build());
    }
}
